### PR TITLE
Add typescript support

### PR DESCRIPTION
**Pull request by ksawery29**
This pull request closes issue #41.

### CODE REVIEW

**Review by ValentinH — COMMENTED** [review]
Thanks for starting this, I'm currently continuing this PR to have stricter typing.

**Comment by ValentinH** [comment]
I'm going to release this as v2.0.0 to ensure we don't break any configuration. Indeed, I'm not super familiar with Svelte nowadays so not really confident ^^

**Comment by ksawery29** [comment]
Looks like tests failed after merge. It seems strange because on my computer it passed without errors. I will look into that.

**Comment by ValentinH** [comment]
Are you referring to Github actions or something else?
I'm currently setting up Github actions as this project was still using CircleCI.

**Comment by ksawery29** [comment]
Yeah, I mean CircleCI. This is the specific [build](https://app.circleci.com/jobs/github/ValentinH/svelte-easy-crop/60)

**Comment by ValentinH** [comment]
Interesting, I'm getting the same issue on Github actions while it's also passing on my machine.

**Comment by ValentinH** [comment]
https://github.com/ValentinH/svelte-easy-crop/releases/tag/v2.0.0

**Pull request merged**
